name: CI

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux:
    name: ${{ matrix.os }}.${{ matrix.compiler.compiler }}.${{ matrix.build-type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ linux ]
        build-type: [ Release ]
        compiler:
          - { compiler: GNU,  CC: gcc-10,   CXX: g++-10 }
          - { compiler: LLVM, CC: clang-10, CXX: clang++-10 }


    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
        SRC_DIR: ${{ github.workspace }}
        BUILD_DIR: ${{ github.workspace }}/build
        INSTALL_PREFIX: ${{ github.workspace }}/install
        BUILD_TYPE: ${{ matrix.build-type }}
      run: |
        cmake -E make_directory "${BUILD_DIR}";
        cmake -E make_directory "${INSTALL_DIR}";
        cmake -B ${BUILD_DIR} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DATZUBI_RTENGINE_BUILD_EXAMPLES=0;
        cmake --build ${BUILD_DIR} --config ${BUILD_TYPE};
      
